const vocabData = [
    // SQL & Query Basics
    { en: "SQL", vn: "Ngôn ngữ truy vấn có cấu trúc" },
    { en: "Structured Query Language", vn: "Ngôn ngữ truy vấn có cấu trúc" },
    { en: "Query", vn: "Truy vấn" },
    { en: "Subquery", vn: "Truy vấn con" },
    { en: "Correlated subquery", vn: "Truy vấn con tương quan" },
    { en: "Noncorrelated subquery", vn: "Truy vấn con không tương quan" },
    { en: "Scalar subquery", vn: "Truy vấn con vô hướng" },
    { en: "Nested query", vn: "Truy vấn lồng nhau" },
    { en: "Result set", vn: "Tập kết quả" },
    { en: "Statement", vn: "Câu lệnh" },
    { en: "Command", vn: "Lệnh" },
    { en: "Clause", vn: "Mệnh đề" },
    { en: "Predicate", vn: "Vị từ (Điều kiện)" },
    { en: "Expression", vn: "Biểu thức" },
    
    // SQL Clauses & Keywords
    { en: "SELECT", vn: "Chọn (Truy vấn)" },
    { en: "FROM", vn: "Từ (Bảng nguồn)" },
    { en: "WHERE", vn: "Mệnh đề điều kiện" },
    { en: "GROUP BY", vn: "Nhóm theo" },
    { en: "HAVING", vn: "Điều kiện cho nhóm" },
    { en: "ORDER BY", vn: "Sắp xếp theo" },
    { en: "DISTINCT", vn: "Khác biệt (Duy nhất)" },
    { en: "AS", vn: "Đặt tên (Bí danh)" },
    { en: "LIKE", vn: "Giống như (So khớp mẫu)" },
    { en: "BETWEEN", vn: "Trong khoảng" },
    { en: "IN", vn: "Trong (danh sách)" },
    { en: "EXISTS", vn: "Tồn tại" },
    { en: "ANY", vn: "Bất kỳ" },
    { en: "ALL", vn: "Tất cả" },
    { en: "IS NULL", vn: "Là giá trị rỗng" },
    { en: "NOT NULL", vn: "Không rỗng" },
    { en: "Ascending", vn: "Tăng dần" },
    { en: "Descending", vn: "Giảm dần" },
    { en: "ASC", vn: "Tăng dần" },
    { en: "DESC", vn: "Giảm dần" },
    
    // Aggregate Functions
    { en: "Aggregate function", vn: "Hàm tổng hợp" },
    { en: "Aggregation", vn: "Tổng hợp dữ liệu" },
    { en: "COUNT", vn: "Đếm" },
    { en: "SUM", vn: "Tính tổng" },
    { en: "AVG", vn: "Tính trung bình" },
    { en: "Average", vn: "Trung bình" },
    { en: "MAX", vn: "Giá trị lớn nhất" },
    { en: "MIN", vn: "Giá trị nhỏ nhất" },
    
    // Join Types
    { en: "Join", vn: "Phép kết nối" },
    { en: "Inner Join", vn: "Kết nối trong" },
    { en: "Outer Join", vn: "Kết nối ngoài" },
    { en: "Left Join", vn: "Kết nối trái" },
    { en: "Left Outer Join", vn: "Kết nối ngoài trái" },
    { en: "Right Join", vn: "Kết nối phải" },
    { en: "Right Outer Join", vn: "Kết nối ngoài phải" },
    { en: "Full Join", vn: "Kết nối đầy đủ" },
    { en: "Full Outer Join", vn: "Kết nối ngoài đầy đủ" },
    { en: "Cross Join", vn: "Tích Đề-các (Kết nối chéo)" },
    { en: "Self Join", vn: "Tự kết nối" },
    { en: "Natural Join", vn: "Kết nối tự nhiên" },
    { en: "Equi-Join", vn: "Kết nối bằng" },
    { en: "Theta Join", vn: "Kết nối theta" },
    
    // Set Operations
    { en: "Union", vn: "Phép hợp" },
    { en: "UNION ALL", vn: "Phép hợp (giữ trùng)" },
    { en: "Intersection", vn: "Phép giao" },
    { en: "INTERSECT", vn: "Phép giao" },
    { en: "Set Difference", vn: "Phép trừ (Hiệu tập hợp)" },
    { en: "EXCEPT", vn: "Phép trừ" },
    { en: "MINUS", vn: "Phép trừ" },
    { en: "Cartesian Product", vn: "Tích Đề-các" },
    
    // DDL Commands
    { en: "DDL", vn: "Ngôn ngữ định nghĩa dữ liệu" },
    { en: "Data Definition Language", vn: "Ngôn ngữ định nghĩa dữ liệu" },
    { en: "CREATE", vn: "Tạo mới" },
    { en: "CREATE TABLE", vn: "Tạo bảng" },
    { en: "CREATE VIEW", vn: "Tạo khung nhìn" },
    { en: "DROP", vn: "Xóa (bảng/CSDL)" },
    { en: "DROP TABLE", vn: "Xóa bảng" },
    { en: "DROP VIEW", vn: "Xóa khung nhìn" },
    { en: "ALTER", vn: "Sửa đổi (cấu trúc)" },
    { en: "ALTER TABLE", vn: "Sửa đổi bảng" },
    { en: "TRUNCATE", vn: "Cắt bớt (Xóa dữ liệu, giữ cấu trúc)" },
    
    // DML Commands
    { en: "DML", vn: "Ngôn ngữ thao tác dữ liệu" },
    { en: "Data Manipulation Language", vn: "Ngôn ngữ thao tác dữ liệu" },
    { en: "INSERT", vn: "Chèn" },
    { en: "INSERT INTO", vn: "Chèn vào" },
    { en: "UPDATE", vn: "Cập nhật" },
    { en: "DELETE", vn: "Xóa (dòng)" },
    
    // DCL Commands
    { en: "DCL", vn: "Ngôn ngữ điều khiển dữ liệu" },
    { en: "Data Control Language", vn: "Ngôn ngữ điều khiển dữ liệu" },
    { en: "GRANT", vn: "Cấp quyền" },
    { en: "REVOKE", vn: "Thu hồi quyền" },
    { en: "Permission", vn: "Quyền hạn" },
    
    // TCL Commands
    { en: "TCL", vn: "Ngôn ngữ điều khiển giao dịch" },
    { en: "Transaction Control Language", vn: "Ngôn ngữ điều khiển giao dịch" },
    { en: "Transaction", vn: "Giao dịch" },
    { en: "COMMIT", vn: "Xác nhận (giao dịch)" },
    { en: "ROLLBACK", vn: "Quay lui (hủy giao dịch)" },
    { en: "SAVEPOINT", vn: "Điểm lưu" },
    
    // Keys
    { en: "Key", vn: "Khóa" },
    { en: "Primary Key", vn: "Khóa chính" },
    { en: "Foreign Key", vn: "Khóa ngoại" },
    { en: "Candidate Key", vn: "Khóa dự tuyển (Khóa ứng viên)" },
    { en: "Superkey", vn: "Siêu khóa" },
    { en: "Super Key", vn: "Siêu khóa" },
    { en: "Composite Key", vn: "Khóa phức hợp" },
    { en: "Partial Key", vn: "Khóa bộ phận" },
    { en: "Alternate Key", vn: "Khóa thay thế" },
    { en: "Unique Key", vn: "Khóa duy nhất" },
    
    // Constraints
    { en: "Constraint", vn: "Ràng buộc" },
    { en: "NOT NULL constraint", vn: "Ràng buộc không rỗng" },
    { en: "UNIQUE constraint", vn: "Ràng buộc duy nhất" },
    { en: "CHECK constraint", vn: "Ràng buộc kiểm tra" },
    { en: "DEFAULT", vn: "Giá trị mặc định" },
    { en: "Referential Integrity", vn: "Toàn vẹn tham chiếu" },
    { en: "Entity Integrity", vn: "Toàn vẹn thực thể" },
    { en: "Domain Integrity", vn: "Toàn vẹn miền" },
    
    // Relational Algebra
    { en: "Relational Algebra", vn: "Đại số quan hệ" },
    { en: "Algebra", vn: "Đại số" },
    { en: "Selection", vn: "Phép chọn (σ)" },
    { en: "Projection", vn: "Phép chiếu (Π)" },
    { en: "Rename", vn: "Phép đổi tên (ρ)" },
    { en: "Sigma", vn: "Sigma (σ) - Phép chọn" },
    { en: "Pi", vn: "Pi (Π) - Phép chiếu" },
    { en: "Rho", vn: "Rho (ρ) - Phép đổi tên" },
    { en: "Unary operation", vn: "Phép toán một ngôi" },
    { en: "Binary operation", vn: "Phép toán hai ngôi" },
    { en: "Procedural", vn: "Thủ tục" },
    { en: "Non-procedural", vn: "Phi thủ tục (Khai báo)" },
    { en: "Declarative", vn: "Khai báo" },
    { en: "Composition", vn: "Phép hợp thành" },
    
    // Operators & Connectives
    { en: "Operator", vn: "Toán tử" },
    { en: "Comparison operator", vn: "Toán tử so sánh" },
    { en: "Logical operator", vn: "Toán tử logic" },
    { en: "Arithmetic operator", vn: "Toán tử số học" },
    { en: "AND", vn: "Và (Toán tử AND)" },
    { en: "OR", vn: "Hoặc (Toán tử OR)" },
    { en: "NOT", vn: "Phủ định (Toán tử NOT)" },
    { en: "Connective", vn: "Liên kết (Logic)" },
    
    // Attributes
    { en: "Attribute", vn: "Thuộc tính" },
    { en: "Simple attribute", vn: "Thuộc tính đơn" },
    { en: "Composite attribute", vn: "Thuộc tính phức hợp" },
    { en: "Multivalued attribute", vn: "Thuộc tính đa trị" },
    { en: "Derived attribute", vn: "Thuộc tính dẫn xuất" },
    { en: "Stored attribute", vn: "Thuộc tính lưu trữ" },
    { en: "Key attribute", vn: "Thuộc tính khóa" },
    { en: "Non-key attribute", vn: "Thuộc tính không khóa" },
    { en: "Prime attribute", vn: "Thuộc tính nguyên tố" },
    { en: "Non-prime attribute", vn: "Thuộc tính không nguyên tố" },
    { en: "Atomic", vn: "Nguyên tử (Không thể chia nhỏ)" },
    
    // Entities & Relationships
    { en: "Entity", vn: "Thực thể" },
    { en: "Entity type", vn: "Kiểu thực thể" },
    { en: "Entity set", vn: "Tập thực thể" },
    { en: "Weak entity", vn: "Thực thể yếu" },
    { en: "Strong entity", vn: "Thực thể mạnh" },
    { en: "Identifying owner", vn: "Thực thể chủ sở hữu" },
    { en: "Associative entity", vn: "Thực thể kết hợp" },
    { en: "Gerund", vn: "Thực thể kết hợp (Gerund)" },
    { en: "Relationship", vn: "Mối quan hệ" },
    { en: "Relationship type", vn: "Kiểu quan hệ" },
    { en: "Recursive relationship", vn: "Mối quan hệ đệ quy" },
    { en: "Unary relationship", vn: "Mối quan hệ một ngôi" },
    { en: "Binary relationship", vn: "Mối quan hệ hai ngôi" },
    { en: "Ternary relationship", vn: "Mối quan hệ ba ngôi" },
    { en: "Degree", vn: "Bậc (của mối quan hệ)" },
    { en: "Cardinality", vn: "Bản số" },
    { en: "Cardinality ratio", vn: "Tỷ lệ bản số" },
    { en: "One-to-One", vn: "Một-một (1:1)" },
    { en: "One-to-Many", vn: "Một-nhiều (1:N)" },
    { en: "Many-to-Many", vn: "Nhiều-nhiều (M:N)" },
    { en: "Participation", vn: "Tham gia (trong quan hệ)" },
    { en: "Total Participation", vn: "Tham gia toàn phần" },
    { en: "Partial Participation", vn: "Tham gia bộ phận" },
    { en: "Mandatory participation", vn: "Tham gia bắt buộc" },
    { en: "Optional participation", vn: "Tham gia tùy chọn" },
    
    // ER Model
    { en: "ER Model", vn: "Mô hình thực thể - quan hệ" },
    { en: "Entity-Relationship", vn: "Thực thể - Quan hệ" },
    { en: "EER Model", vn: "Mô hình ER mở rộng" },
    { en: "Enhanced ER", vn: "ER mở rộng" },
    { en: "Crow's Foot notation", vn: "Ký hiệu chân gà" },
    { en: "Chen notation", vn: "Ký hiệu Chen" },
    
    // Generalization & Specialization
    { en: "Generalization", vn: "Tổng quát hóa" },
    { en: "Specialization", vn: "Chuyên biệt hóa" },
    { en: "Supertype", vn: "Kiểu cha (Siêu kiểu)" },
    { en: "Subtype", vn: "Kiểu con" },
    { en: "Inheritance", vn: "Kế thừa" },
    { en: "Disjoint", vn: "Rời rạc" },
    { en: "Overlap", vn: "Chồng lặp" },
    { en: "Total completeness", vn: "Toàn vẹn toàn phần" },
    { en: "Partial completeness", vn: "Toàn vẹn bộ phận" },
    { en: "Completeness constraint", vn: "Ràng buộc toàn vẹn (đầy đủ)" },
    { en: "Discriminator", vn: "Thuộc tính phân loại" },
    
    // Normalization
    { en: "Normalization", vn: "Chuẩn hóa" },
    { en: "Denormalization", vn: "Phi chuẩn hóa" },
    { en: "Normal Form", vn: "Dạng chuẩn" },
    { en: "1NF", vn: "Dạng chuẩn 1" },
    { en: "First Normal Form", vn: "Dạng chuẩn 1" },
    { en: "2NF", vn: "Dạng chuẩn 2" },
    { en: "Second Normal Form", vn: "Dạng chuẩn 2" },
    { en: "3NF", vn: "Dạng chuẩn 3" },
    { en: "Third Normal Form", vn: "Dạng chuẩn 3" },
    { en: "BCNF", vn: "Dạng chuẩn Boyce-Codd" },
    { en: "Boyce-Codd Normal Form", vn: "Dạng chuẩn Boyce-Codd" },
    { en: "4NF", vn: "Dạng chuẩn 4" },
    { en: "Fourth Normal Form", vn: "Dạng chuẩn 4" },
    { en: "5NF", vn: "Dạng chuẩn 5" },
    { en: "Fifth Normal Form", vn: "Dạng chuẩn 5" },
    
    // Dependencies
    { en: "Dependency", vn: "Phụ thuộc" },
    { en: "Functional Dependency", vn: "Phụ thuộc hàm" },
    { en: "Full Functional Dependency", vn: "Phụ thuộc hàm đầy đủ" },
    { en: "Partial Dependency", vn: "Phụ thuộc bộ phận" },
    { en: "Partial Functional Dependency", vn: "Phụ thuộc hàm bộ phận" },
    { en: "Transitive Dependency", vn: "Phụ thuộc bắc cầu" },
    { en: "Multivalued Dependency", vn: "Phụ thuộc đa trị" },
    { en: "Trivial Dependency", vn: "Phụ thuộc tầm thường" },
    { en: "Determinant", vn: "Định thức (Yếu tố quyết định)" },
    { en: "Dependent", vn: "Phụ thuộc (Yếu tố bị quy định)" },
    
    // Armstrong's Axioms
    { en: "Armstrong's Axioms", vn: "Tiên đề Armstrong" },
    { en: "Reflexivity", vn: "Tính phản xạ" },
    { en: "Augmentation", vn: "Tính tăng cường" },
    { en: "Transitivity", vn: "Tính bắc cầu" },
    { en: "Decomposition", vn: "Phân rã" },
    { en: "Pseudo transitivity", vn: "Bắc cầu giả" },
    { en: "Closure", vn: "Bao đóng" },
    { en: "Attribute closure", vn: "Bao đóng thuộc tính" },
    
    // Anomalies
    { en: "Anomaly", vn: "Dị thường (trong dữ liệu)" },
    { en: "Insertion Anomaly", vn: "Dị thường chèn" },
    { en: "Deletion Anomaly", vn: "Dị thường xóa" },
    { en: "Modification Anomaly", vn: "Dị thường sửa đổi" },
    { en: "Update Anomaly", vn: "Dị thường cập nhật" },
    { en: "Redundancy", vn: "Dư thừa dữ liệu" },
    { en: "Data Redundancy", vn: "Dư thừa dữ liệu" },
    
    // Database Structure
    { en: "Database", vn: "Cơ sở dữ liệu" },
    { en: "DBMS", vn: "Hệ quản trị CSDL" },
    { en: "Database Management System", vn: "Hệ quản trị cơ sở dữ liệu" },
    { en: "RDBMS", vn: "Hệ quản trị CSDL quan hệ" },
    { en: "Relational Database", vn: "Cơ sở dữ liệu quan hệ" },
    { en: "Relational Model", vn: "Mô hình quan hệ" },
    { en: "Table", vn: "Bảng" },
    { en: "Relation", vn: "Quan hệ (Bảng)" },
    { en: "Tuple", vn: "Bộ (Hàng)" },
    { en: "Row", vn: "Hàng" },
    { en: "Record", vn: "Bản ghi" },
    { en: "Column", vn: "Cột" },
    { en: "Field", vn: "Trường" },
    { en: "Schema", vn: "Lược đồ" },
    { en: "Instance", vn: "Thể hiện (Dữ liệu)" },
    { en: "Domain", vn: "Miền giá trị" },
    { en: "Virtual table", vn: "Bảng ảo" },
    { en: "View", vn: "Khung nhìn (View)" },
    { en: "Alias", vn: "Bí danh" },
    
    // Data Types
    { en: "Data type", vn: "Kiểu dữ liệu" },
    { en: "VARCHAR", vn: "Chuỗi ký tự biến đổi" },
    { en: "CHAR", vn: "Chuỗi ký tự cố định" },
    { en: "INTEGER", vn: "Số nguyên" },
    { en: "INT", vn: "Số nguyên" },
    { en: "DECIMAL", vn: "Số thập phân" },
    { en: "NUMERIC", vn: "Số" },
    { en: "FLOAT", vn: "Số thực" },
    { en: "DATE", vn: "Ngày" },
    { en: "DATETIME", vn: "Ngày giờ" },
    { en: "BOOLEAN", vn: "Logic (Đúng/Sai)" },
    { en: "TEXT", vn: "Văn bản" },
    { en: "BLOB", vn: "Dữ liệu nhị phân lớn" },
    
    // Database Abstraction
    { en: "Abstraction", vn: "Trừu tượng hóa" },
    { en: "Data abstraction", vn: "Trừu tượng hóa dữ liệu" },
    { en: "Physical level", vn: "Mức vật lý" },
    { en: "Logical level", vn: "Mức logic" },
    { en: "View level", vn: "Mức khung nhìn" },
    { en: "External level", vn: "Mức ngoài" },
    { en: "Conceptual level", vn: "Mức khái niệm" },
    { en: "Internal level", vn: "Mức trong" },
    
    // Database Design
    { en: "Database Design", vn: "Thiết kế CSDL" },
    { en: "Conceptual Design", vn: "Thiết kế khái niệm" },
    { en: "Logical Design", vn: "Thiết kế logic" },
    { en: "Physical Design", vn: "Thiết kế vật lý" },
    { en: "Requirements Analysis", vn: "Phân tích yêu cầu" },
    
    // Integrity
    { en: "Integrity", vn: "Tính toàn vẹn" },
    { en: "Data Integrity", vn: "Toàn vẹn dữ liệu" },
    { en: "Consistency", vn: "Tính nhất quán" },
    { en: "Atomicity", vn: "Tính nguyên tử" },
    { en: "Isolation", vn: "Tính cô lập" },
    { en: "Durability", vn: "Tính bền vững" },
    { en: "ACID", vn: "Các thuộc tính ACID" },
    
    // Miscellaneous
    { en: "Wildcard", vn: "Ký tự đại diện" },
    { en: "Pattern", vn: "Mẫu" },
    { en: "Index", vn: "Chỉ mục" },
    { en: "Trigger", vn: "Trigger (Trình kích hoạt)" },
    { en: "Stored Procedure", vn: "Thủ tục lưu trữ" },
    { en: "Function", vn: "Hàm" },
    { en: "Cursor", vn: "Con trỏ" },
    { en: "Identifier", vn: "Định danh" },
    { en: "Metadata", vn: "Siêu dữ liệu" },
    { en: "Data Dictionary", vn: "Từ điển dữ liệu" },
    { en: "Catalog", vn: "Danh mục hệ thống" },
    { en: "Null", vn: "Rỗng (Giá trị Null)" },
    { en: "Unique", vn: "Duy nhất" },
    { en: "Scalar", vn: "Vô hướng" },
    { en: "Logical", vn: "(Thuộc về) Logic" },
    { en: "Physical", vn: "(Thuộc về) Vật lý" },
    { en: "Temporary", vn: "Tạm thời" },
    { en: "Permanent", vn: "Vĩnh viễn" },
    { en: "Filter", vn: "Lọc" },
    { en: "Sort", vn: "Sắp xếp" },
    { en: "Group", vn: "Nhóm" },
    { en: "Combined", vn: "Kết hợp" },
    { en: "Model", vn: "Mô hình" },
    { en: "Match", vn: "Khớp" },
    { en: "Purpose", vn: "Mục đích" },
    { en: "Represent", vn: "Đại diện (Biểu diễn)" },
    { en: "Include", vn: "Bao gồm" },
    { en: "Retrieve", vn: "Truy xuất" },
    { en: "Identify", vn: "Xác định" },
    { en: "Condition", vn: "Điều kiện" },
    { en: "Duplicate", vn: "Trùng lặp" },
    { en: "Duplicates", vn: "Các bản sao trùng" },
    { en: "Remove duplicates", vn: "Loại bỏ trùng lặp" },
    { en: "User", vn: "Người dùng" },
    { en: "Role", vn: "Vai trò" },
    { en: "Portability", vn: "Tính di động" },
    { en: "Standard", vn: "Tiêu chuẩn" },
    { en: "ANSI", vn: "Viện tiêu chuẩn Mỹ" },
    
    // Example Entities
    { en: "Employee", vn: "Nhân viên" },
    { en: "Department", vn: "Phòng ban" },
    { en: "Salary", vn: "Lương" },
    { en: "Customer", vn: "Khách hàng" },
    { en: "Order", vn: "Đơn hàng" },
    { en: "Product", vn: "Sản phẩm" },
    { en: "Supplier", vn: "Nhà cung cấp" },
    { en: "Enrollment", vn: "Ghi danh" },
    { en: "Instructor", vn: "Giảng viên" },
    { en: "Student", vn: "Sinh viên" },
    { en: "Course", vn: "Môn học" },
    { en: "Semester", vn: "Học kỳ" },
    { en: "Grade", vn: "Điểm số" },
    { en: "Project", vn: "Dự án" },
    { en: "Manager", vn: "Quản lý" },
    { en: "Skill", vn: "Kỹ năng" },

    // Additional Terms from Quiz
    { en: "Access", vn: "Truy cập" },
    { en: "Application", vn: "Ứng dụng" },
    { en: "Backup", vn: "Sao lưu" },
    { en: "Collection", vn: "Bộ sưu tập" },
    { en: "Computed", vn: "Được tính toán" },
    { en: "Context", vn: "Ngữ cảnh" },
    { en: "Duplication", vn: "Sự trùng lặp" },
    { en: "Environment", vn: "Môi trường" },
    { en: "Execute", vn: "Thực thi" },
    { en: "Format", vn: "Định dạng" },
    { en: "Hardware", vn: "Phần cứng" },
    { en: "Hierarchical", vn: "Phân cấp" },
    { en: "Implementation", vn: "Triển khai" },
    { en: "Inconsistency", vn: "Sự không nhất quán" },
    { en: "Independent", vn: "Độc lập" },
    { en: "Information", vn: "Thông tin" },
    { en: "Input", vn: "Đầu vào" },
    { en: "Interacts", vn: "Tương tác" },
    { en: "Loss", vn: "Mất mát" },
    { en: "Maintenance", vn: "Bảo trì" },
    { en: "Mandatory", vn: "Bắt buộc" },
    { en: "Mapping", vn: "Ánh xạ" },
    { en: "Network", vn: "Mạng" },
    { en: "Object", vn: "Đối tượng" },
    { en: "Optional", vn: "Tùy chọn" },
    { en: "Organization", vn: "Tổ chức" },
    { en: "Output", vn: "Đầu ra" },
    { en: "Outage", vn: "Sự cố gián đoạn" },
    { en: "Performance", vn: "Hiệu suất" },
    { en: "Portability", vn: "Tính di động" },
    { en: "Power", vn: "Nguồn điện" },
    { en: "Prevention", vn: "Ngăn chặn" },
    { en: "Processing", vn: "Xử lý" },
    { en: "Property", vn: "Thuộc tính" },
    { en: "Ratio", vn: "Tỷ lệ" },
    { en: "Referencing relation", vn: "Quan hệ tham chiếu" },
    { en: "Referenced relation", vn: "Quan hệ được tham chiếu" },
    { en: "Requirement", vn: "Yêu cầu" },
    { en: "Retrieval", vn: "Truy xuất" },
    { en: "Security", vn: "Bảo mật" },
    { en: "Semantics", vn: "Ngữ nghĩa" },
    { en: "Simultaneous", vn: "Đồng thời" },
    { en: "Software", vn: "Phần mềm" },
    { en: "Storage", vn: "Lưu trữ" },
    { en: "Structure", vn: "Cấu trúc" },
    { en: "Structured", vn: "Có cấu trúc" },
    { en: "Subset", vn: "Tập con" },
    { en: "Syntax", vn: "Cú pháp" },
    { en: "Transfer", vn: "Chuyển" },
    { en: "Validate", vn: "Xác thực" },
    { en: "Value", vn: "Giá trị" },
    { en: "Variable", vn: "Biến" },
    { en: "Verify", vn: "Xác minh" },

    // Database Operations
    { en: "CASCADE", vn: "Lan truyền (xóa/cập nhật)" },
    { en: "ON DELETE CASCADE", vn: "Xóa lan truyền" },
    { en: "ON UPDATE CASCADE", vn: "Cập nhật lan truyền" },
    { en: "SET NULL", vn: "Đặt giá trị NULL" },
    { en: "RESTRICT", vn: "Hạn chế" },
    { en: "AUTO_INCREMENT", vn: "Tự động tăng" },
    { en: "IDENTITY", vn: "Định danh tự động" },

    // Query Terms
    { en: "Matching", vn: "Khớp" },
    { en: "Unmatched", vn: "Không khớp" },
    { en: "Compatible", vn: "Tương thích" },
    { en: "Comparison", vn: "So sánh" },
    { en: "Condition", vn: "Điều kiện" },
    { en: "Eliminate", vn: "Loại bỏ" },
    { en: "Empty", vn: "Rỗng" },
    { en: "Entire", vn: "Toàn bộ" },
    { en: "Execution", vn: "Thực thi" },
    { en: "Finding", vn: "Tìm kiếm" },
    { en: "Grouping", vn: "Nhóm" },
    { en: "Hierarchy", vn: "Phân cấp" },
    { en: "Immediately", vn: "Ngay lập tức" },
    { en: "Included", vn: "Bao gồm" },
    { en: "Minimal", vn: "Tối thiểu" },
    { en: "Multiple", vn: "Nhiều" },
    { en: "Occurrence", vn: "Sự xuất hiện" },
    { en: "Present", vn: "Hiện tại / Có mặt" },
    { en: "Previous", vn: "Trước đó" },
    { en: "Produces", vn: "Tạo ra" },
    { en: "Proper", vn: "Đúng đắn / Thích hợp" },
    { en: "Range", vn: "Phạm vi" },
    { en: "Resulted", vn: "Kết quả" },
    { en: "Returns", vn: "Trả về" },
    { en: "Similar", vn: "Tương tự" },
    { en: "Single", vn: "Đơn lẻ" },
    { en: "Specified", vn: "Được chỉ định" },
    { en: "Symbol", vn: "Ký hiệu" }
];
